//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BasicDemo.rc
//
#define IDOK2                           3
#define ID_SAVE                         3
#define IDOK3                           4
#define ID_LOAD                         4
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_BasicDemo_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     130
#define IDD_Setting_DIALOG              130
#define IDI_HPC_ICON                    140
#define IDI_SETTING_ICON                141
#define IDD_LOG_VIEW_DIALOG             142
#define IDI_LOG_HISTORY_ICON            144
#define IDC_ENUM_BUTTON                 1000
#define IDC_OPEN_BUTTON                 1001
#define IDC_CLOSE_BUTTON                1002
#define IDC_CONTINUS_MODE_RADIO         1003
#define IDC_TRIGGER_MODE_RADIO          1004
#define IDC_START_GRABBING_BUTTON       1005
#define IDC_STOP_GRABBING_BUTTON        1006
#define IDC_SOFTWARE_ONCE_BUTTON        1007
#define IDC_SOFTWARE_TRIGGER_CHECK      1008
#define IDC_SAVE_BMP_BUTTON             1009
#define IDC_SAVE_JPG_BUTTON             1010
#define IDC_EXPOSURE_EDIT               1011
#define IDC_GAIN_EDIT                   1012
#define IDC_FRAME_RATE_EDIT             1013
#define IDC_GET_PARAMETER_BUTTON        1014
#define IDC_SET_PARAMETER_BUTTON        1015
#define IDC_DEVICE_COMBO                1016
#define IDC_INIT_STATIC                 1017
#define IDC_IMAGE_GRABBING_STATIC       1018
#define IDC_SAVE_IMAGE_STATIC           1019
#define IDC_PARAMETER_STATIC            1020
#define IDC_EXPOSURE_STATIC             1021
#define IDC_GAIN_STATIC                 1022
#define IDC_FRAME_RATE_STATIC           1023
#define IDC_DISPLAY_STATIC              1024
#define IDC_SAVE_TIFF_BUTTON            1025
#define IDC_SETTING_BUTTON              1026
#define IDC_SAVE_PNG_BUTTON             1027
#define IDC_SHIRMP_NUMBER_STATIC        1028
#define IDC_BUTTON1                     1029
#define IDC_STOP_COUNT_BUTTON           1029
#define IDC_BUTTON2                     1030
#define IDC_BUTTON                      1030
#define IDC_START_COUNT_BUTTON          1030
#define IDC_BUTTON3                     1031
#define IDC_RESET_NUMBER_BUTTON         1031
#define IDC_EDIT1                       1032
#define IDC_F1_EDIT                     1032
#define IDC_TOLERANCE_X                 1032
#define IDC_ROI_X0                      1032
#define IDC_EDIT2                       1033
#define ID_AVG_AREA                     1033
#define IDC_EDIT3                       1034
#define ID_BSG_HISTORY                  1034
#define IDC_EDIT4                       1035
#define ID_BSG_THRESHOLD                1035
#define IDC_EDIT5                       1036
#define IDC_COMBO1                      1036
#define IDC_FRAME_COUNT_EDIT            1036
#define ID_BLUR_KERNEL                  1036
#define IDC_EDIT6                       1037
#define IDC_COMBO2                      1037
#define IDC_ROI_IN_FRAME_EDIT           1037
#define ID_BSG_SHADOW                   1037
#define IDC_EDIT7                       1038
#define IDC_COMBO3                      1038
#define IDC_SHRIMP_IN_FRAME_EDIT        1038
#define ID_MORPHO_METHOD                1038
#define IDC_SETTING_BUTTON2             1039
#define IDC_COMBO4                      1039
#define IDC_LOG_BUTTON                  1039
#define ID_MORPHO_KERNEL                1039
#define IDC_EDIT8                       1040
#define ID_IOU_THRESHOLD                1040
#define ID_DISTANCE_THRESHOLD           1040
#define IDC_EDIT9                       1041
#define IDC_AVG_SIZE_EDIT               1041
#define ID_MIN_HITS                     1041
#define IDC_EDIT10                      1042
#define IDC_F2_EDIT                     1042
#define ID_MAX_AGE                      1042
#define IDC_EDIT11                      1043
#define IDC_F3_EDIT                     1043
#define ID_LINE_POSITION                1043
#define IDC_EDIT12                      1044
#define ID_MAX_DISTANCE                 1044
#define IDC_F4_EDIT                     1044
#define IDC_EDIT13                      1045
#define ID_MIN_AREA                     1045
#define IDC_EDIT14                      1046
#define ID_MIN_WIDTH                    1046
#define IDC_EDIT15                      1047
#define ID_MIN_HEIGHT                   1047
#define IDC_COMBO5                      1048
#define ID_BSG_METHOD                   1048
#define IDC_COMBO6                      1049
#define ID_BLUR_MEDTHOD                 1049
#define ID_OK                           1050
#define ID_CANCEL                       1051
#define ID_BSG_METHOD2                  1052
#define ID_ADAPTIVETHRESHOLD_METHOD     1052
#define ID_BSG_THRESHOLD2               1053
#define ID_ADAPTIVETHRESHOLD_KSIZE      1053
#define ID_BSG_THRESHOLD3               1054
#define ID_ADAPTIVETHRESHOLD_C          1054
#define IDC_RADIO_BACKGROUNDSUBTRACTION 1055
#define IDC_RADIO_ADAPTIVETHRESHOLD     1056
#define IDC_RADIO_My_Tracking           1057
#define IDC_ROI_WIDTH                   1057
#define ID_MAX_AREA                     1058
#define IDC_RADIO_SORT_TRACKING         1059
#define IDC_ROI_Y0                      1059
#define IDC_LIST3                       1060
#define IDC_LOG_HISTORY_LIST            1060
#define ID_MAX_WIDTH                    1060
#define ID_LOG_OK                       1061
#define ID_MAX_HEIGHT                   1061
#define ID_LOG_CANCLE                   1062
#define ID_LOG_CLEAR_DATA               1062
#define ID_FLIP_IMAGE                   1062
#define ID_BSG_HISTORY2                 1063
#define ID_BSG_LEARNING_RATE            1063
#define IDC_EDIT18                      1064
#define IDC_ROI_HEIGHT                  1064
#define IDC_MORPHO_ITERATIONS           1071

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1072
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
